// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-J1YceZJ-otFZg_tQXeXPR4tazifr4YY',
    appId: '1:611028858136:web:85cd19b8fd480d62ea5a6d',
    messagingSenderId: '611028858136',
    projectId: 'mobile-crowds-8d603',
    authDomain: 'mobile-crowds-8d603.firebaseapp.com',
    databaseURL: 'https://mobile-crowds-8d603-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-crowds-8d603.appspot.com',
    measurementId: 'G-4MHXB4ZW3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKhxknH2B_kCsirLPXMQu60qPMWuF_bh0',
    appId: '1:611028858136:android:13f623c0fc13848aea5a6d',
    messagingSenderId: '611028858136',
    projectId: 'mobile-crowds-8d603',
    databaseURL: 'https://mobile-crowds-8d603-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-crowds-8d603.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO_kNZVXnifIDQ2MPuyKfRus4UbJ71cnc',
    appId: '1:611028858136:ios:1ad13f4616aa7c2cea5a6d',
    messagingSenderId: '611028858136',
    projectId: 'mobile-crowds-8d603',
    databaseURL: 'https://mobile-crowds-8d603-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-crowds-8d603.appspot.com',
    androidClientId: '611028858136-m56htlbe47i35ut7b1650sp5vtrmo264.apps.googleusercontent.com',
    iosClientId: '611028858136-4lkqfk7buf9km8r24ht8arq07a1e5v24.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileCrowdsApp',
  );
}
